In [1]:
import numpy as np

In [2]:
np.__version__ #used to check the version of library

'2.3.5'

In [3]:
##Create & Read 

In [4]:
####1D Array

In [10]:
arr1 = np.array([1,2,3,4,5,6]) #for creating an array
arr1 #used to display the content

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr1) #used to check the datatype

numpy.ndarray

In [11]:
arr1.shape #elements

(6,)

In [12]:
 arr1.dtype

dtype('int64')

In [13]:
arr1.ndim

1

In [14]:
arr1.size

6

In [15]:
####2D Array

In [17]:
arr2 = np.array([[1,2,3],[7,8,9]]) #used to create the 2-D array
arr2 #prints it

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
arr2.ndim #used to identify the dimension of array

2

In [19]:
arr2.dtype

dtype('int64')

In [20]:
arr2.size

6

In [21]:
####3D Array

In [29]:
arr3 = np.array([[[1,4,5],[6,7,4]],[[3,4,5],[5,8,7]],[[1,4,5],[6,7,4]]]) #used to create the 3-D array
arr3 #prints it

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [30]:
arr3.ndim

3

In [31]:
arr3.shape

(3, 2, 3)

In [32]:
arr3.size

18

In [33]:
###Create random array

In [34]:
randomArr =np.random.rand(3, 2, 3) #create a 3D Array with random values
randomArr #prints it

array([[[0.80275372, 0.33812207, 0.63133237],
        [0.70967383, 0.54990388, 0.31332149]],

       [[0.7219447 , 0.49522632, 0.40036947],
        [0.03816035, 0.55915558, 0.95240192]],

       [[0.19256045, 0.43514689, 0.75746427],
        [0.02284612, 0.4145092 , 0.83747355]]])

In [35]:
randomArr.dtype #type

dtype('float64')

In [37]:
full = np.full((3, 2, 3), 9) #create the array with all elements 9
full #prints it

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [38]:
ones = np.ones((3,2,3)) #create the array with all elements 1
ones #prints it

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [40]:
arr3[0][0][2] #access the specific element

np.int64(5)

In [41]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [42]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]]])

In [43]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [44]:
arr3[1][0][1]

np.int64(4)

In [45]:
arr3[1,0,1]

np.int64(4)

In [46]:
#Update & Delete

In [47]:
a1 = np.random.rand(2,3,2) #2 random arrays
a2 = np.random.rand(2,3,2)

In [48]:
a1 #1

array([[[0.2215252 , 0.46287848],
        [0.67036841, 0.10435948],
        [0.3262923 , 0.15279477]],

       [[0.45323861, 0.93630925],
        [0.11254191, 0.18758471],
        [0.76187303, 0.1925059 ]]])

In [49]:
a2 #2

array([[[0.94267243, 0.34613248],
        [0.63468012, 0.58665699],
        [0.31621745, 0.39940843]],

       [[0.16993169, 0.28881531],
        [0.37162211, 0.50524509],
        [0.69352983, 0.62484537]]])

In [51]:
#BASIC MATH OPERATIONS

In [52]:
np.add(a1, a2) #addition

array([[[1.16419762, 0.80901096],
        [1.30504853, 0.69101648],
        [0.64250975, 0.5522032 ]],

       [[0.6231703 , 1.22512456],
        [0.48416402, 0.6928298 ],
        [1.45540286, 0.81735126]]])

In [53]:
np.subtract(a1,a2) #subtraction

array([[[-0.72114723,  0.116746  ],
        [ 0.03568829, -0.48229751],
        [ 0.01007485, -0.24661365]],

       [[ 0.28330691,  0.64749395],
        [-0.2590802 , -0.31766038],
        [ 0.0683432 , -0.43233947]]])

In [54]:
np.multiply(a1,a2)

array([[[0.20882569, 0.16021727],
        [0.4254695 , 0.06122322],
        [0.10317932, 0.06102752]],

       [[0.0770196 , 0.27042044],
        [0.04182306, 0.09477625],
        [0.52838168, 0.12028642]]])

In [55]:
np.divide(a1,a2)

array([[[0.23499701, 1.33728703],
        [1.05623036, 0.17788842],
        [1.03186052, 0.3825527 ]],

       [[2.66718112, 3.24189624],
        [0.30283966, 0.37127467],
        [1.09854399, 0.30808566]]])

In [56]:
#STATISTICAL OPERTIONS

In [62]:
sqrt = np.sqrt(25) #finds the square root of the given number
sqrt 

np.float64(5.0)

In [63]:
abs = np.abs(-2)
abs

np.int64(2)

In [68]:
power = np.power(2,8) #calculates the power of 2 raise to 8
power

np.int64(256)

In [65]:
log = np.log(25) #finds the log value
log

np.float64(3.2188758248682006)

In [66]:
mins = np.min(a1) #finds the minimum value from the array
mins

np.float64(0.10435948374593618)

In [67]:
maxs = np.max(a2) #finds the maximum value from the array
maxs

np.float64(0.9426724254286171)

In [ ]:
#UPDATE

In [69]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [70]:
arr3[0,0,2] = 50 #updates the value from the specific element of an array
arr3

array([[[ 1,  4, 50],
        [ 6,  7,  4]],

       [[ 3,  4,  5],
        [ 5,  8,  7]],

       [[ 1,  4,  5],
        [ 6,  7,  4]]])

In [71]:
#RESHAPE

In [72]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[ 1,  4, 50],
        [ 6,  7,  4],
        [ 3,  4,  5]],

       [[ 5,  8,  7],
        [ 1,  4,  5],
        [ 6,  7,  4]]])

In [80]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [76]:
new_array = np.ones((3,2,3)) #creates an array of value 1
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
appd = np.append(zeroes,new_array,axis=1) #axis 0 = row,axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [83]:
#DELETE

In [85]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.81206867, 0.63346966, 0.25433026],
        [0.2655105 , 0.16160123, 0.27467016]],

       [[0.06874133, 0.20390051, 0.62979159],
        [0.85551158, 0.70837568, 0.67327561]],

       [[0.14130588, 0.56644469, 0.83474676],
        [0.4571442 , 0.46355919, 0.05434561]]])

In [86]:
arr5 = np.delete(arr4, 0, axis=1)

In [87]:
arr5

array([[[0.2655105 , 0.16160123, 0.27467016]],

       [[0.85551158, 0.70837568, 0.67327561]],

       [[0.4571442 , 0.46355919, 0.05434561]]])

In [88]:
np.save("new_array",arr5) #create new file for the array

In [90]:
np.load("new_array.npy") #loades the specific file

array([[[0.2655105 , 0.16160123, 0.27467016]],

       [[0.85551158, 0.70837568, 0.67327561]],

       [[0.4571442 , 0.46355919, 0.05434561]]])